services:
  web:
    build:
      context: .
      dockerfile: Containerfile
    env_file: .env
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - nostr_shared

  updater:
    build:
      context: .
      dockerfile: Containerfile
    env_file: .env
    entrypoint: ["/updater_entrypoint.sh"]
    networks:
      - nostr_shared
    restart: unless-stopped

networks:
  nostr_shared:
    external: true
