services:
  web:
    build:
      context: .
      dockerfile: Containerfile
    env_file: .env
    ports:
      - "127.0.0.1:8020:8000"
    networks:
      - nostr_shared

networks:
  nostr_shared:
    external: true
